import type { Metadata } from "next";
import "@/app/globals.css";
import localFont from "next/font/local";
import Header from "@/app/components/Header";

const alphino = localFont({
  src: "./fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alphino",
});

export const metadata: Metadata = {
  title: "Fizzi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alphino.variable} antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
