import type { Metadata } from "next";
import "@/app/globals.css";
import localFont from "next/font/local";
import Header from "@/app/components/Header";
import ViewCanvas from "@/app/components/ViewCanvas";

const alpino = localFont({
  src: "./fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export const metadata: Metadata = {
  title: "Fizzi",
  description: "Generated by create next app",
  icons: "/icon.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={alpino.variable}>
      <body className={`antialiased overflow-x-hidden bg-yellow-300`}>
        <Header />
        <main>
          {children}
          <ViewCanvas />
        </main>
      </body>
    </html>
  );
}
